development:
  adapter: postgresql
  database: seattle_parking_development
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  database: seattle_parking_test
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  database: db/production.sqlite3
  pool: 5
  timeout: 5000
